name: curl_generator
description: Generate curl command

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^1.1.0
  state_notifier: ^0.7.2+1
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  freezed: ^1.1.1

flutter:
  uses-material-design: true
